### ISSUE TITLE
60 byte transmission limit in rfm9xfsk_rh_simpletest.py

### ISSUE THREAD

**Issue by joeesser1842** [jerryneedell/CircuitPython_RFM#1]
Is there a reason for the 60 byte limit when transmitting? I can't find anything in the code or datasheet that would indicate this limit exists.

**Comment by jerryneedell** [comment]
Oops. That is a cut/paste error.The limit for the RFM9x should be 252 bytes.  The RFM69 only supports 60. Thanks. I'll clean that up.

**Comment by jerryneedell** [comment]
Updated the comments regarding the packet length in this commit https://github.com/jerryneedell/CircuitPython_RFM/commit/0ec464a39eee8b0403b3abed8e2bcbb0a8fc64ff
